# A file for non-class related utility and constants

SCREEN_WIDTH, SCREEN_HEIGHT = 1000, 600
PLAYER_HEALTH = 10
BIGGIE_WIDTH, BIGGIE_HEIGHT = 40, 60
TRACY_WIDTH, TRACY_HEIGHT = 40, 30
ACTIVE = None
LEVEL_WIDTH,LEVEL_HEIGHT = 2100, 3000
PLATFORM_WIDTH = PLATFORM_HEIGHT = 32